package com.example.contrackt_me.util

import com.example.contrackt_me.model.JobRequest
import com.google.firebase.database.FirebaseDatabase

class FirebaseHelper private constructor() {
    private val database = FirebaseDatabase.getInstance(Constants.DB_BASE_URL)
    private val jobRequestsRef = database.getReference(Constants.DB_JOB_REQUESTS_NODE)
    // todo: add reference to users node
    // todo: add reference to contractors node

    // key is uniquely generated by firebase.
    fun submitJobRequest(jobRequest: JobRequest) {
        val newJobRequestInstance = jobRequestsRef.push()
        newJobRequestInstance.setValue(jobRequest)
    }

    // todo: add methods for users
    // todo: add methods for contractors

    // singleton instance
    companion object {
        private var helperInstance: FirebaseHelper? = null

        @Synchronized
        fun getInstance(): FirebaseHelper {
            if (helperInstance == null) {
                helperInstance = FirebaseHelper()
            }
            return helperInstance!!
        }
    }
}